In [1]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import time_evolutor as te
import plotting as p

import sys
sys.path.append('/../../temp_prog/')
import tur_calculator as tc



In [2]:
#------------------SETUP-------------------

T_L = 25 
T_R = 10
V_B = 30
eps = 50

INPUT = {
    'eps': eps,
    'omega': 0, 
    'u': 250, 
    'V_B': V_B,
    'gamma': 1,  
    'T_L': T_L,
    'T_R': T_R
}

initial = [1/4,1/4,1/4,1/4,0,0]
ti_array = np.linspace(0,1e5,10000)

In [5]:
importlib.reload(te)
liouvillian, dim, eval_j, left_ev, right_ev = te.parallel_liouvillian(initial, ti_array, **INPUT)

[[ 1. -0.  0. -0. -0. -0.]
 [-0.  1.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-0. -0.  0.  1. -0.  0.]
 [-0. -0.  0. -0.  1.  0.]
 [-0. -0.  0.  0. -0.  1.]]
check l1 is identity: [-0.189  0.189  0.189  0.567 -0.756  0.   ]


In [10]:
print(right_ev[0])
print(right_ev[1])
print(right_ev[2])
print(right_ev[3])
print(right_ev[4])
print(right_ev[5])

print(right_ev.shape)

[-8.34483850e-01  9.52189369e-01  0.00000000e+00 -5.87346888e-16
 -3.06584443e-01  7.55928946e-01]
[ 0.30308461  0.19128057  0.         -0.70710678 -0.21478321 -0.37796447]
[ 0.30308461  0.19128057  0.          0.70710678 -0.21478321 -0.37796447]
[ 1.09484732e-06  5.61882370e-07  0.00000000e+00  8.47860169e-17
  7.36150864e-01 -3.31512601e-22]
[-3.46289104e-01 -1.41982005e-01  0.00000000e+00  1.70152955e-16
  5.21367654e-01 -3.77964473e-01]
[0. 0. 1. 0. 0. 0.]
(6, 6)


In [8]:
print(eval_j)

[ 3.00679023e-17+0.j -1.93067802e-16+0.j -1.90155272e+00+0.j
 -1.90155272e+00+0.j -4.00000000e+00+0.j -4.00000000e+00+0.j]


In [11]:
print(left_ev[0])
print(left_ev[1])

[-0.18870743  0.41828932  0.          0.          0.          0.03977736]
[ 1.89188311e-01  4.91822447e-01  0.00000000e+00 -7.07106781e-01
 -8.43002492e-07 -3.84145079e-01]


In [19]:
eigen = right_ev[0]
result = liouvillian@eigen


for idx, ev in enumerate(eval_j):
    #print(ev*right_ev[idx])
    print(liouvillian@right_ev[idx])

[ 8.08975134e-01 -1.30980935e+00  5.00828936e-01  5.27839474e-06
 -4.04484928e-01 -1.43743874e+00]
[-0.51279005 -1.33968225 -0.97595215  2.82842445  1.67060725  0.71871937]
[-0.51279005  1.48874011  1.8524702  -2.82842026 -1.15781511  0.71871937]
[ 2.79965524e+00 -1.39982567e+00 -1.39982461e+00 -4.96460584e-06
 -1.39983010e+00  6.30388688e-22]
[ 1.78101163e+00 -7.55510684e-01 -1.02549695e+00 -3.99487185e-06
 -8.90507813e-01  7.18719372e-01]
[ 1.90154935e+00  0.00000000e+00 -1.90155272e+00  3.37200428e-06
 -9.50772988e-01  0.00000000e+00]
