In [1]:
import sys
sys.path.append('/../../QmeQ/qmeq/')
#sys.path.append('../qmeq/')
import qmeq
import numpy as np

In [2]:
#--SETUP: ---------------------------------------------------------------------------------
epsilons = np.linspace(-100, 100, 10)
omega = 0.105
u_intra = 500
u_inter = 300
V_B = 50
mu_L = -V_B/2       
mu_R = V_B/2        

gammaL = 0.1
gammaR = gammaL
tL = np.sqrt(gammaL/np.pi/2)
tR = np.sqrt(gammaR/np.pi/2)
T_L = 10
T_R = 1
n = 4
nleads = 4

U = {(0,1,1,0):u_intra, (2,3,3,2):u_intra, (0,2,2,0):u_inter, (0,3,3,0):u_inter, (1,2,2,1):u_inter, (1,3,3,1):u_inter } 
mulst = {0:mu_L, 1:mu_L, 2:mu_R, 3:mu_R}
tlst = {0:T_L, 1:T_L, 2:T_R, 3:T_R}

if T_L < T_R:
    raise SystemExit("Not my convention! (T_L < T_R) so cell was shut down")
elif T_L > T_R:
    T_COLD = T_R
    T_HOT = T_L
elif T_L == T_R:
    raise SystemExit("Not a heat engine (T_L = T_R) so cell was shut down")

In [3]:
eps = 500
#double QD in series (with spin) ==============================================================================================================
h = {(0,0):eps, (1,1):eps, (2,2):eps, (3,3):eps, (0,2):omega, (1,3):omega} # <-------/// Här skiljer dom sig ! ///----
tleads = {(0, 0):tL, (1, 1):tL, (2, 2):tR, (3, 3):tR} # <------/// Här skiljer dom sig ! ///----

system_parallell = qmeq.Builder(nsingle=n, hsingle=h, coulomb=U, nleads=nleads,
                         mulst=mulst, tlst=tlst, tleads=tleads, dband=1e4, countingleads=[0,1], kerntype='pyLindblad')
system_parallell.solve()
print('IN SERIES: Standard current:',system_parallell.current)
print('IN SERIES: Counting currents and noise at the left lead (Lindblad):',system_parallell.current_noise)

#double QD in parallel (with spin) ===========================================================================================================
h = {(0,0):eps, (1,1):eps, (2,2):eps, (3,3):eps} # <------/// Här skiljer dom sig ! ///-----
tleads = {(0, 0):tL, (1, 1):tL, (2, 2):tR, (3, 3):tR, (0,2):tL, (1,3):tL, (2,0):tR, (3,1):tR} # <-------/// Här skiljer dom sig ! ///----
#============================================================================================================================================

system_parallell = qmeq.Builder(nsingle=n, hsingle=h, coulomb=U, nleads=nleads,
                         mulst=mulst, tlst=tlst, tleads=tleads, dband=1e4, countingleads=[0,1], kerntype='pyLindblad')
system_parallell.solve()
print('IN PARALLEL: Standard current:',system_parallell.current)
print('IN PARALLEL: Counting currents and noise at the left lead (Lindblad):',system_parallell.current_noise)

IN SERIES: Standard current: [ 6.45327834e-25  6.45327834e-25 -6.45327834e-25 -6.45327834e-25]
IN SERIES: Counting currents and noise at the left lead (Lindblad): [1.29065567e-24 1.29065567e-24]
IN PARALLEL: Standard current: [ 1.58321429e-24  1.58321429e-24 -1.58321429e-24 -1.58321429e-24]
IN PARALLEL: Counting currents and noise at the left lead (Lindblad): [3.16642857e-24 3.16642857e-24]


In [4]:
x = np.linspace(0,3, 3)
y = np.sin(x)


xv, yv = np.meshgrid(x, y, indexing='ij')
print('1:')
print('xv',xv)
print('yv',yv)

xv, yv = np.meshgrid(x, y, indexing='xy')
print('2:')
print('xv',xv)
print('yv',yv)


1:
xv [[0.  0.  0. ]
 [1.5 1.5 1.5]
 [3.  3.  3. ]]
yv [[0.         0.99749499 0.14112001]
 [0.         0.99749499 0.14112001]
 [0.         0.99749499 0.14112001]]
2:
xv [[0.  1.5 3. ]
 [0.  1.5 3. ]
 [0.  1.5 3. ]]
yv [[0.         0.         0.        ]
 [0.99749499 0.99749499 0.99749499]
 [0.14112001 0.14112001 0.14112001]]
